// <auto-generated />
using System;
using Feedbacktool;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Feedbacktool.Api.Data.Migrations
{
    [DbContext(typeof(ToolContext))]
    [Migration("20250916090832_AddExerciseItems")]
    partial class AddExerciseItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Feedbacktool.Models.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ClassGroups", (string)null);
                });

            modelBuilder.Entity("Feedbacktool.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Feedbacktool.Models.ExerciseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseItems");
                });

            modelBuilder.Entity("Feedbacktool.Models.ExerciseItemResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseItemId")
                        .HasColumnType("integer");

                    b.Property<string>("GivenAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("ScoreRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseItemId");

                    b.HasIndex("ScoreRecordId");

                    b.ToTable("ExerciseItemResult");
                });

            modelBuilder.Entity("Feedbacktool.Models.ScoreGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Name")
                        .IsUnique();

                    b.ToTable("ScoreGroups", (string)null);
                });

            modelBuilder.Entity("Feedbacktool.Models.ScoreRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("ScoreRecords");
                });

            modelBuilder.Entity("Feedbacktool.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Feedbacktool.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserScoreGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreGroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ScoreGroupId");

                    b.HasIndex("ScoreGroupId");

                    b.ToTable("UserScoreGroups", (string)null);
                });

            modelBuilder.Entity("UserSubject", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("UserSubjects", (string)null);
                });

            modelBuilder.Entity("Feedbacktool.Models.Exercise", b =>
                {
                    b.HasOne("Feedbacktool.Models.Subject", "Subject")
                        .WithMany("Exercises")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Feedbacktool.Models.ExerciseItem", b =>
                {
                    b.HasOne("Feedbacktool.Models.Exercise", "Exercise")
                        .WithMany("Items")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Feedbacktool.Models.ExerciseItemResult", b =>
                {
                    b.HasOne("Feedbacktool.Models.ExerciseItem", "ExerciseItem")
                        .WithMany()
                        .HasForeignKey("ExerciseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedbacktool.Models.ScoreRecord", "ScoreRecord")
                        .WithMany("ItemResults")
                        .HasForeignKey("ScoreRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseItem");

                    b.Navigation("ScoreRecord");
                });

            modelBuilder.Entity("Feedbacktool.Models.ScoreGroup", b =>
                {
                    b.HasOne("Feedbacktool.Models.Subject", "Subject")
                        .WithMany("ScoreGroups")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Feedbacktool.Models.ScoreRecord", b =>
                {
                    b.HasOne("Feedbacktool.Models.Exercise", "Exercise")
                        .WithMany("ScoreRecords")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedbacktool.Models.User", "User")
                        .WithMany("ScoreRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Feedbacktool.Models.User", b =>
                {
                    b.HasOne("Feedbacktool.Models.ClassGroup", "ClassGroup")
                        .WithMany("Users")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassGroup");
                });

            modelBuilder.Entity("UserScoreGroup", b =>
                {
                    b.HasOne("Feedbacktool.Models.ScoreGroup", null)
                        .WithMany()
                        .HasForeignKey("ScoreGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedbacktool.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserSubject", b =>
                {
                    b.HasOne("Feedbacktool.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feedbacktool.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Feedbacktool.Models.ClassGroup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Feedbacktool.Models.Exercise", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ScoreRecords");
                });

            modelBuilder.Entity("Feedbacktool.Models.ScoreRecord", b =>
                {
                    b.Navigation("ItemResults");
                });

            modelBuilder.Entity("Feedbacktool.Models.Subject", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("ScoreGroups");
                });

            modelBuilder.Entity("Feedbacktool.Models.User", b =>
                {
                    b.Navigation("ScoreRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
